name: Rust CI

on:
  push:
    branches: [main, dev, test]
  pull_request:
    branches: [main, dev, test]

env:
  CARGO_AUDIT_VERSION: 0.21.2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-registry-

      - name: Cache Cargo build
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-build-

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Run Clippy
        run: cargo clippy -- -D warnings

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Cache cargo binaries
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bin-${{ env.CARGO_AUDIT_VERSION }}
          restore-keys: ${{ runner.os }}-cargo-bin-

      - name: Install cargo-audit (if not cached)
        run: |
          if ! command -v cargo-audit &> /dev/null; then
            cargo install cargo-audit --version $CARGO_AUDIT_VERSION
          fi

      - name: Run cargo audit
        run: cargo audit
